server:
  port: 9999

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://localhost:3306/db_pms?charset=utf8&useSSL=false
    username: root
    password: liuqiang1997
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: localhost
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: 3000
        max-idle: 8
        min-idle: 0
    timeout: 1000

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    #   开启发送确认
    publisher-confirm-type: CORRELATED
    #   开启发送return模式
    publisher-returns: true
    connection-timeout: 3000

    template:
      #     配合return机制使用，表示接收路由不可达的消息
      mandatory: true

    listener:
      direct:
        #        手动ack
        acknowledge-mode: manual
        retry:
          enabled: true


# 配置mybatis-plus

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.liuqiang.model

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 配置日志
logging:
  file:
    name: log/log.log
  level:
    root: info
    com.security.securitydemo: debug

